version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DB_NAME: "wordpress"
      TZ: "America/Sao_Paulo"
    volumes:
      - /mnt/efs:/var/www/html
    networks:
      - wp-network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_ROOT_PASSWORD: "root_password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
